name: appimage

on:
  workflow_run:
    workflows: ["development"]
    types:
      - completed

jobs:
  build-appimage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # Use oldest ubuntu to make AppImage work
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-default libqt5svg5-dev
      - name: Build application
        run: |
          cd ${GITHUB_WORKSPACE}/application
          qmake
          make -j`nproc`
      - name: Generate AppImage
        run: |
          sudo apt-get install -y libfuse2
          cd ${GITHUB_WORKSPACE} && sh ./ci/appimage/bundle.sh
      - name: Archive AppImage
        uses: actions/upload-artifact@v3
        with:
          name: Dust3D-x86_64.AppImage
          path: Dust3D-x86_64.AppImage