name: Deploying

on:
  push:
    branches:
      - master
      - pipeline
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Run clang-format
        run: cd ${GITHUB_WORKSPACE}/ci && sh ./lint.sh && cd ${GITHUB_WORKSPACE}
      - name: Check for changes
        run: |
          if ! git diff --ignore-space-at-eol --exit-code; then
            exit 1
          fi
  build:
    # Use oldest ubuntu to make AppImage work
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-default libqt5svg5-dev
      - name: Build application
        run: |
          cd ${GITHUB_WORKSPACE}/application
          qmake
          make -j`nproc`
      - name: Generate AppImage
        run: |
          sudo apt-get install -y libfuse2
          cd ${GITHUB_WORKSPACE} && sh ./ci/appimage/bundle.sh
      - name: Archive AppImage
        uses: actions/upload-artifact@v3
        with:
          path: Dust3D-x86_64.AppImage