name: Deploying

on: [push]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Run clang-format
        run: cd ${GITHUB_WORKSPACE}/ci && sh ./lint.sh && cd ${GITHUB_WORKSPACE}
      - name: Check for changes
        run: |
          if ! git diff --ignore-space-at-eol --exit-code; then
            exit 1
          fi
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake libqt5svg5-dev
      - name: Build application
        run: |
          cd ${GITHUB_WORKSPACE}/application
          qmake
          make